# This is a basic workflow that is manually triggered

name: Release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: debian-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build AppImage
        run: ./portable2appimage APP-MANAGER APP-MANAGER 10.5 "ivan-hc|AM|latest"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "workdir/*"
          token: ${{ secrets.GITHUB_TOKEN }}
