name: AppImage release workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. 10.5.1)'
        required: true
        type: string
      message:
        description: 'Release message'
        required: false
        type: string
        default: 'Latest build. See commits for detailed changes: https://github.com/ivan-hc/AM/commits/main'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build AppImage
        run: ./portable2appimage APP-MANAGER APP-MANAGER 10.5 "ivan-hc|AM|latest"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          body: "Latest build. See commits for detailed changes: https://github.com/ivan-hc/AM/commits/main"
          artifacts: "*.AppImage,*.AppImage.zsync"
          token: ${{ secrets.GITHUB_TOKEN }}
